### ISSUE TITLE
Outstanding fixes from PR #166

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#188]
/bug

After PR # 166 (PipelineRun with embedded pipelineSpec) there are some test cases that still need to be fixed:

- [ ] **big_data_passing.yaml** (@fenglixa is working on #189)
- [ ] **input_artifact_raw_value.yaml** (might depend on `big_data_passing` fix)
  - `unknown field "artifacts"` ... missing `stepTemplate` with `volumeMounts`
- [ ] **pipelineparams.yaml** (might depend on `big_data_passing` fix)
  - `[download : main] sh: results.downloaded-resultoutput.path: not found`
- [ ] **pipeline_transformers.yaml** (Tekton dependency)
  - missing task/pod annotations

_Originally posted by @ckadner in https://github.com/kubeflow/kfp-tekton/pull/166#issuecomment-645031702_

**Comment by Tomcli** [comment]
also tag #152 for double check artifacts after big data passing is done.

**Comment by ckadner** [comment]
@animeshsingh

**Comment by animeshsingh** [comment]
- [ ] **input_artifact_raw_value.yaml** (might depend on `big_data_passing` fix)
  - `unknown field "artifacts"` ... missing `stepTemplate` with `volumeMounts`
- [ ] **pipelineparams.yaml** (might depend on `big_data_passing` fix)
  - `[download : main] sh: results.downloaded-resultoutput.path: not found`

Just highlighting so that its on @fenglixa radar

**Comment by fenglixa** [comment]
Below items are fixed in PR #194:
- [x] big_data_passing.yaml (@fenglixa is working on #189)
- [x] input_artifact_raw_value.yaml (might depend on big_data_passing fix)
* unknown field "artifacts" ... missing stepTemplate with volumeMounts
- [x] pipelineparams.yaml (might depend on big_data_passing fix)
* [download : main] sh: results.downloaded-resultoutput.path: not found

The last item should be fixed as well, @ckadner , could you please double confirm?
- [ ] pipeline_transformers.yaml (Tekton dependency)
* missing task/pod annotations
