### ISSUE TITLE
Python 3.5 deprecation

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#200]
KFP is planning deprecation for Python 3.5 
What's the impact on this project + Watson implementation, and concerns we want to raise

@Tomcli @ckadner @Udiknedormin @fenglixa

**Comment by ckadner** [comment]
I don't see any issues from a SDK implementation perspective. In fact the code will get better if we drop support for Python 3.5. But there may be issues with bundled packages that allow or rely on Python 3.5 (i.e. TFX?) and with Linux platforms that come with Python 3.5.

Linking the discussion from KFP PR 668  that has been open since January 2019:
https://github.com/kubeflow/pipelines/pull/668

> https://github.com/kubeflow/pipelines/pull/668#issuecomment-517800032
>> Please don't bump the minimum allowed Python version without documenting the pros and cons of doing so. This will break backwards compatibility with clients who rely on KFP like the TFX DSL, and so should only be done with care. Ideally, there should be a document-based discussion around this proposal before doing this.

> https://github.com/kubeflow/pipelines/pull/668#issuecomment-486557326
>> The problem is that Python 3.6 is not available on the latest stable Debian Linux (even though it was released several years ago). https://packages.debian.org/search?keywords=python3

**Comment by fenglixa** [comment]
My self python was 3.6, and I didn't find any issues on it for kfp-tekton.

**Comment by Tomcli** [comment]
Closing this, there's no hard dependency for Python 3.5 and we will be supporting the same python releases as KFP.
