### ISSUE TITLE
KFP UI: Update graph to accept the new Tekton finally syntax

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#219]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
Tekton introduced a new finally syntax in 0.14.0. Here is an example generated with our kfp sdk.
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/exit_handler.py

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli, I'll take a look. Since anything marked "finally" is inherently going to be waiting on "non-finally" marked tasks how should the graph structure look for these exit handler tasks? Should there be an edge from every non-finally task to the finally tasks or should there only be edges from tasks that pass parameters to these finally tasks?

**Comment by Tomcli** [comment]
For the finally task, you can treat them as the regular Tekton node except the UI node background is mild yellow. So only show edges from tasks that pass parameters to these finally tasks.

https://github.com/kubeflow/pipelines/blob/master/frontend/src/lib/WorkflowParser.ts#L69-L79 In Argo it is called exit handler.
