### ISSUE TITLE
Rebase to KFP 1.0

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#224]
https://github.com/kubeflow/pipelines/tree/1.0.0-rc.5

**Comment by Tomcli** [comment]
FYI we should rebase using the official release from today
https://github.com/kubeflow/pipelines/releases/tag/1.0.0

Tasks:
- [ ] Backend
- [ ] Frontend
- [ ] SDK
- [ ] Manifest

**Comment by Tomcli** [comment]
Additional tasks for 1.0 multiusers:
- [ ] Implement a separate KFP-Tekton controller for injecting default S3 credentials for artifacts. In multi-user, pipelines are not suppose to mount on a secret, instead it should be injected by the runtime controller. (This feature is part of the new Argo controller, but since Tekton has not yet implement the concept of artifact, we need to add our own custom implementation via webhook injection)
- [ ] Create configmap for KFP-Tekton specific config. For artifact and logging, we have our own implementation because Tekton doesn't support it out of the box. Therefore, we need a dedicated configmap to conifigure the settings on our artifact and logging archive.

**Comment by ckadner** [comment]
The KFP 1.0.0 Rebase is a work in progress that requires collaboration between API, UI, SDK experts. 

**Proposed process:**
- PR #244 targets the `kfp-1.0-rebase` branch, @Tomcli @drewbutlerbb4 review it, minor comments can be addressed there and if there are no obvious problems we merge that PR
- @Tomcli and @drewbutlerbb4 checkout the `kfp-1.0-rebase` branch locally and push further PRs to the the `kfp-1.0-rebase` branch with additional code changes that are required to make the API and UI work with the KFP 1.0 code base
- after all PRs on the `kfp-1.0-rebase` branch are merged, the `kfp-tekton-bot` squashes all commits from the `kfp-1.0-rebase` branch and creates a single PR onto the `master` branch with all consolidate _KFP 1.0 rebase/merge_ changes

**Comment by Tomcli** [comment]
Side note: The artifact and execution page doesn't have pagination because the metadata has not yet support it, so users will try query all artifacts (including the ones owned by other users) when they land the artifact page which can be slow for frequently use. 

Tracking issue: https://github.com/kubeflow/pipelines/issues/3226

**Comment by Tomcli** [comment]
For the new artifact design with multi user, we are planning to move on to tekton 0.15 for using new context variables as our s3 key. This way the implementation can be a bit more close to argo.
https://github.com/tektoncd/pipeline/blob/master/docs/variables.md
