### ISSUE TITLE
KFP-Tekton V0.3 Plan

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#225]
Support for

1. Log archival and storage
  https://github.com/kubeflow/kfp-tekton/issues/198
2. Multi-user pipelines
https://github.com/kubeflow/kfp-tekton/issues/199
https://github.com/kubeflow/pipelines/issues/1223
3. Upgrade to KFP 1.0
https://github.com/kubeflow/kfp-tekton/issues/224
https://github.com/kubeflow/pipelines/tree/1.0.0-rc.5

cc @Tomcli @ckadner @fenglixa

**Comment by Tomcli** [comment]
In addition, we need to fix these issues for our 0.3 release:
4. Add SDK Support for 'volumeClaimTemplate' to dynamically create PVC https://github.com/kubeflow/kfp-tekton/issues/181
5. (Nice to have) Add prow for testing. This may require upstream merging for SDK and sample directory design.
6. (Nice to have) Refactor the origin Argo interface into an abstracted common interface. However, we should do it when we plan to merge back to KFP because we will need to maintain 3 different interfaces (common, Argo, Tekton) instead of the one Tekton interface we have now. https://github.com/kubeflow/kfp-tekton-backend/issues/7

**Comment by Tomcli** [comment]
done
/close
