### ISSUE TITLE
Investigate different ways to pass parameters between tasks

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#41]
Currently, we are using the [task.results](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#results) for passing parameter outputs. This has a limitation where the output parameter files have to be under `/tekton/results`. However, some of the Kubeflow pipeline has no configuration for the output file path (e.g. The current [Watson ML example](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/ibm-samples/watson)).  Therefore, we need to figure out an alternative way that can take output parameter files from any path in the container.

**Comment by ckadner** [comment]
PR #27

**Comment by Tomcli** [comment]
initial proposal, adding an extra step to copy file to `/tekton/results`

**Comment by Tomcli** [comment]
update: passing file between steps will still require either volumemount or [workspaces](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#configuring-workspaces). 
However, both of them still requires to specify a mountpath that's not `/`. Therefore, it won't be scalable if users store their file in more than one subpath.

**Comment by Tomcli** [comment]
init poc branch: https://github.com/Tomcli/kfp-tekton/tree/copy_param

**Comment by Tomcli** [comment]
right now we don't have code-gen for pipelinerun. So creating workspaces will require user to manually define their workspace volumes. Should we propose to also generate pipelinerun as part of our yaml?

**Comment by ckadner** [comment]
@afrittoli -- can you clarify if we really need a `Workspace` (and a `PipelineRun` to mount the volume) here? We are just trying to add an additional step to those `tasks` which have output parameters which need to be moved to the default `/tekton/results` folder

**Comment by Tomcli** [comment]
Added initial approach to copy the files with an extra step. @afrittoli let me know if you could think of a better way to pass parameters in any path.

**Comment by afrittoli** [comment]
> update: passing file between steps will still require either volumemount or [workspaces](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md#configuring-workspaces).
> However, both of them still requires to specify a mountpath that's not `/`. Therefore, it won't be scalable if users store their file in more than one subpath.

For sharing between steps you can mount an `emptyDir`, however that would not work for sharing across tasks. You could use an empty dir that mounts to `/kfp` and transform user provided paths to be relative to that i.e. `/tmp/output.txt` would be `/kfp/tmp/output.txt` in the Tekton YAML.

**Comment by afrittoli** [comment]
> @afrittoli -- can you clarify if we really need a `Workspace` (and a `PipelineRun` to mount the volume) here? We are just trying to add an additional step to those `tasks` which have output parameters which need to be moved to the default `/tekton/results` folder

As long as you're within the boundaries of a Task, you don't need a `Workspace`.
Workspaces are an useful abstraction that allows you to avoid embeeding the name of a PVC into the static definition of a Task/Pipeline - so that you can bind any PVC to the workspace at runtime. You don't need workspaces for file sharing between steps, you can use the node filesystem for that, mount an emtpy dir to any path you like (except `/tekton`, which is reserved).

**Comment by afrittoli** [comment]
As a side not, I feel that allowing absolute paths into the KFP DSL is a leak of a lower level detail into the DSL abstraction, but I guess it might be too late to change that?
As a data scientist / machine learning engineer, I would like to create Pipeline operations with named outputs - how this outputs are stored into file within the containers is not something I should worry about. The only file interface should be when I want to export data to a permanent storage so that it's available outside of the pipeline.
