### ISSUE TITLE
Fix big data passing

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#63]
Re-implement the [`fix_big_data_passing`](https://github.com/kubeflow/kfp-tekton/blob/00504fe8493b1c41423dfd5323bff6e1ccbaae04/sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py#L18-L65) function, which converts a workflow where some artifact data is passed as parameters and converts it to a workflow where this data is passed as artifacts.

This method is currently only a No-op pass-through in the KFP-Tekton compiler:
```Python
def fix_big_data_passing(workflow: Dict[Text, Any]) -> Dict[Text, Any]: 
    """
    No-op
    """
    return workflow
```

### Motivation

Due to the convoluted nature of the DSL compiler, the artifact consumption and passing has been implemented on top of that using parameter passing. The artifact data is passed as parameters and the consumer template creates an artifact/file out of that data.

Due to the limitations of Kubernetes (and Argo, Tekton) this scheme cannot pass data larger than few kilobytes preventing any serious use of artifacts.

The `fix_big_data_passing` function rewrites the compiled workflow so that the data consumed as artifact is passed as artifact. It also prunes the unused parameter outputs. This is important since if a big piece of data is ever returned through a file that is also output as parameter, the execution will fail. This makes is possible to pass large amounts of data.

### Implementation in KFP

1. Index the DAGs to understand how data is being passed and which inputs/outputs are connected to each other.
2. Search for direct data consumers in container/resource templates and some DAG task attributes (e.g. conditions and loops) to find out which inputs are directly consumed as parameters/artifacts.
3. Propagate the consumption information upstream to all inputs/outputs all the way up to the data producers.
4. Convert the inputs, outputs and arguments based on how they're consumed downstream.

### KFP implementation

See `kubeflow/pipelines`: [`sdk/python/kfp/compiler/_data_passing_rewriter.py`](https://github.com/kubeflow/pipelines/blob/3df29394c1f70298071fc94a77ecd36e9a32d606/sdk/python/kfp/compiler/_data_passing_rewriter.py#L6)

**Comment by Tomcli** [comment]
This is the original code from kfp
https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler/_data_passing_rewriter.py

This big data passing has very complex processing to convert local files into artifact passing methods in a very Argo specific way. We would love to see can we reuse some of these methods so that we don't have to maintain our version of big data passing.

**Comment by Tomcli** [comment]
@ckadner this new example in KFP should able to reproduce this issue. 
https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/Data%20passing%20in%20python%20components/Data%20passing%20in%20python%20components%20-%20Files.py

**Comment by fenglixa** [comment]
> this new example in KFP should able to reproduce this issue.

@Tomcli , I tried this example, but it works well with current kfp-tekton:
```
$ tkn p start file-passing-pipelines --showlog
Pipelinerun started: file-passing-pipelines-run-f6cjf
Waiting for logs to be available...

[split-text-lines : copy-inputs] + echo -n 'one
[split-text-lines : copy-inputs] two
[split-text-lines : copy-inputs] three
[split-text-lines : copy-inputs] four
[split-text-lines : copy-inputs] five
[split-text-lines : copy-inputs] six
[split-text-lines : copy-inputs] seven
[split-text-lines : copy-inputs] eight
[split-text-lines : copy-inputs] nine
[split-text-lines : copy-inputs] ten'
```

We may need to find another example/use cases, which could easy reproduce the issues for big data fix.  Thanks!

**Comment by animeshsingh** [comment]
@fenglixa can you connect with Michalina @@Udiknedormin internally

**Comment by fenglixa** [comment]
Get the issues, ans also synced with Michalina, I will try to provide PR later, which will address the items as below:

1. There is no `fix_big_data_passing` function in kfp-tekton now, will re-implement it for kfp-tekton.
2. Handle Output -> OutputPath, Input -> InputPath for big data passing, a potential solution is using `workspaces` instead of result if the parameter outputs is bigger data.
3. Fix big data passing pipelinerun error of: “Could not find result with name xxx for task run xxx”
4. Remove unused parameter outputs
5. Big data fix makes results multiplied: output A of step X is present in both X and copy-artifacts step injected by the compiler, Tekton takes both
6. copy-artifacts only copies them out, for output artefacts, but doesn't copy them to the by-artifact inputs of consumers

Please append your comments here, if any concerns. Thanks

**Comment by animeshsingh** [comment]
Thanks @fenglixa for prioritizing it. We need this to unblock Watson
