### ISSUE TITLE
Create new SDK helper functions for embedding exception handlers as part of the DSL

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#912]
/kind feature

**Description:**
The exception handlers in Watson Studio pipelines are custom tasks that ran inside the exit handle. The exception handlers spec is a Tekton pipeline spec that trigger another pipelinerun (similar to the sub pipeline concept for pipelineloop, but for exit handlers).

Thus, we need to create new SDK helper functions similar to the `loop()` class where this new function can use python `with` block to construct a sub-pipeline spec using python `with` enter and exit logics.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yhwang** [comment]
the syntax could be:
```python
from kfp_tekton.tekton import ExceptionHandler

@dsl.pipeline(
    name='exception-handler',
    description='simple pipeline.'
)
def pipeline():
    ExceptionHandler():
        task1()
        task2()
```
@Udiknedormin any comments?

**Comment by yhwang** [comment]
this SDK change would create a hard dependency with the exception-handler mechanism. the compiler would generate a corresponding part for the exception handling steps defined in the helper function. if we use custom task to do that, we should also export the implementation under `tekton-catalog` directory?

**Comment by Udiknedormin** [comment]
@yhwang
I assume `ExceptionHandler` will be some configurable class of some kind, right?

As for your question about exporting implementation to `tekton-catalog` --- quite the opposite, actually. What is needed is reasonably generic way to create pipeline-based custom tasks, similar to how task-like custom tasks can be generated right now. That way, it should be possible to add not only `ExceptionHandler` but also any other pipeline-like custom tasks.

That way, the implementation doesn't need to be present in tekton-catalog because the details of the custom task are provided by the DSL user themselves, similarly to task-like custom tasks.

What we need for sure is to be able to specify input parameters for that kind of custom-task, and to support those input parameters inside of the pipeline body, similar to how loops may define params such as `from`-`step`-`end` that have constant names, and an extra parameter with dynamic name defined in the `iterateParam` field.

I'm not sure if we can do all of that with `with XYZ():` syntax. How about the following?

```python
with ExceptionHandler(
  foo, # fixed-name param
  bar=bar, # dynamic-name param
)(stacktrace_param='bar') as params:
  foo = params['first']
  bar = params['bar']
  task1()
  task2()
```

or:

```python
with ExceptionHandler.with_dynamic(
  fixed={'first': foo},
  dynamic={'stacktrace_param': {'name': 'bar', 'value': bar},
) as params:
  foo = params['first']
  bar = params['bar']
  task1()
  task2()
```
a function decorator would be ok too:
```python
@exception_handler(stacktrace_param='bar')
def exc_handler(first: str, bar: str) -> None:
  task1()
  task2()

exc_handler(foo, bar)
```
Please note that dealing with dynamic parameters is not as much of a priority --- we'd much rather get an working implementations with only fixed parameters available earlier rather than a fully reconfigurable custom-task implementation much later.
